_type: export
__export_format: 4
__export_date: 2022-01-05T06:54:45.331Z
__export_source: insomnia.desktop.app:v2021.7.2
resources:
  - _id: req_wrk_a255aeabb44240f5885e3360f9a6ee6523acbe44
    parentId: fld_wrk_a255aeabb44240f5885e3360f9a6ee651b034c38
    modified: 1641196273388
    created: 1641195562173
    url: '{{ base_url }}/wkwkw'
    name: Add a new pet to the store
    description: ''
    method: POST
    body:
      mimeType: application/json
      text: |-
        {
          "id": 10,
          "name": "doggie",
          "category": {
            "id": 1,
            "name": "Dogs"
          },
          "photoUrls": [
            "string"
          ],
          "tags": [
            {
              "id": 0,
              "name": "string"
            }
          ],
          "status": "string"
        }
    parameters: []
    headers:
      - name: Content-Type
        value: application/json
        id: pair_3ade684a900c4a33ab96cc51362c5257
    authentication: {}
    metaSortKey: -1641195562173
    isPrivate: false
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: env_env_e36ff964c604633ac012e67acde4790806dc20c8_sub
    parentId: env_e36ff964c604633ac012e67acde4790806dc20c8
    modified: 1641196328832
    created: 1641195562181
    name: OpenAPI env
    data:
      scheme:
        - https
      base_path: /v3
      host: petstore3.swagger.io/api
      apiKey: apiKey
    dataPropertyOrder:
      '&':
        - scheme
        - base_path
        - host
        - apiKey
    color: null
    isPrivate: false
    metaSortKey: 1641195562181
    _type: environment
