services:
  prometheus:
    image: prom/prometheus
    container_name: monika_prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    network_mode: host
