probes:
  - id: '1'
    requests:
      - url: http://idntimes.com
notifications:
  - id: unique-id-monika-notif
    type: desktop
  - id: random-string-mailgun
    type: mailgun
    data:
      recipients: ['muslim.hyperjumptech@gmail.com']
      apiKey: b6ab69dcf47a1f9e2158dea34a8c09b5-64574a68-715a3e71
      domain: sandbox77920c4e2f5a47e9aa9ef735585a4c0c.mailgun.org