FROM node:14-alpine

# Setup environment variables
ARG PARAMS
ENV PARAMS=${PARAMS}

# Copy files
WORKDIR /monika
COPY package*.json ./
RUN npm ci
COPY . .

# Install
RUN npm run prepack
RUN npm pack
RUN npm install -g --unsafe-perm ./hyperjumptech-monika-*.tgz

# Install PM2 to run Monika
WORKDIR /

CMD ["sh", "-c", "monika ${PARAMS}"]
