FROM node:14-alpine

# Setup environment variables
ARG PARAMS
ENV PARAMS=${PARAMS}

# Install Monika
RUN npm install -g @hyperjumptech/monika

# Run Monika with Params
CMD ["sh", "-c", "monika ${PARAMS}"]
