name: monika
version: git
summary: Synthetic monitoring made easy
description: Monika is a command line monitoring tool
confinement: devmode
grade: stable
base: core20

apps:
  monika:
    command: bin/run

parts:
  monika:
    plugin: dump
    source: ./monika.tar.gz
