name: monika
version: git
summary: Synthetic monitoring made easy
description: Monika is a command line monitoring tool
confinement: devmode
grade: stable
base: core20

apps:
  monika:
    command: bin/run

parts:
  monika:
    plugin: dump
    source: ./monika.tar.gz
    override-pull: |
      sudo apt-get install -y jq curl
      CLI_VERSION=$(curl https://api.github.com/repos/dennypradipta/monika/releases/latest -s | jq .name -r)
      snapcraftctl set-version $CLI_VERSION
      snapcraftctl pull
