name: monika
adopt-info: monika
source-code: https://github.com/hyperjumptech/monika.git
website: https://monika.hyperjump.tech
summary: Synthetic monitoring made easy
description: |
  Monika is a command-line application for synthetic monitoring. The name Monika stands for "Monitoring Berkala", which means "periodic monitoring" in the Indonesian language.

  Please see the [overview](https://hyperjumptech.github.io/monika/overview) to see documentation on how to install and how to use Monika.
confinement: devmode
license: MIT
grade: stable
base: core20

apps:
  monika:
    command: bin/run

parts:
  monika:
    plugin: dump
    source: ./monika.tar.gz
    override-pull: |
      sudo apt-get install -y jq curl
      CLI_VERSION=$(curl https://api.github.com/repos/dennypradipta/monika/releases/latest -s | jq .tag_name -r)
      snapcraftctl set-version $CLI_VERSION
      snapcraftctl pull
