probes:
  - id: '[BODY-NONE] Hyperjump GitHub'
    name: '[BODY-NONE] Hyperjump GitHub'
    requests:
      - url: https://api.github.com/users/hyperjumptech
        method: GET
        headers: {}
        timeout: 10000
    alerts: []
  - id: '[BODY-FORMDATA] Hyperjump GitHub'
    name: '[BODY-FORMDATA] Hyperjump GitHub'
    requests:
      - url: https://api.github.com/users/hyperjumptech
        method: GET
        headers:
          Content-Type: multipart/form-data
        timeout: 10000
        body:
          message: Hello, world!
    alerts: []
  - id: '[BODY-URLENCODED] Hyperjump GitHub'
    name: '[BODY-URLENCODED] Hyperjump GitHub'
    requests:
      - url: https://api.github.com/users/hyperjumptech
        method: GET
        headers:
          Content-Type: application/x-www-form-urlencoded
        timeout: 10000
        body:
          message: Hello, world!
    alerts: []
  - id: '[BODY-RAW-TEXT] Hyperjump GitHub'
    name: '[BODY-RAW-TEXT] Hyperjump GitHub'
    requests:
      - url: https://api.github.com/users/hyperjumptech
        method: GET
        headers:
          Content-Type: text/plain
        timeout: 10000
        body: Hello, world!
    alerts: []
  - id: '[BODY-RAW-JSON] Hyperjump GitHub'
    name: '[BODY-RAW-JSON] Hyperjump GitHub'
    requests:
      - url: https://api.github.com/users/hyperjumptech
        method: GET
        headers:
          Content-Type: application/json
        timeout: 10000
        body:
          message: Hello, world!
    alerts: []
notifications:
  - id: default
    type: desktop
