probes:
  - id: probe-01
    requests:
      - url: http://github.com

notifications:
  - id: unique-id-workplace
    type: workplace
    data:
      thread_id: 'abcdef12345678910'
      access_token: your_custom_integration_access_token
