# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci
            - run: npm run build --if-present
            - run: npm test
            - name: Notify Teams
              uses: joelwmale/webhook-action@fd99bb3b8272237103e349e9bb4d9b0ead9a217c
              with:
                url: ${{secrets.HYPERJUMP_TEAMS_SYMON_WEBHOOK}}
                body: '{"sections": [{"activityTitle": "Monika NPM Release (hook test)", "activitySubtitle": "Version: x.y.z"}]}'
