# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: get-npm-version
              id: package-version
              uses: martinbeentjes/npm-get-version-action@master
            - name: Notify Teams
              uses: joelwmale/webhook-action@fd99bb3b8272237103e349e9bb4d9b0ead9a217c
              with:
                url: https://hyperjump.webhook.office.com/webhookb2/604ef4ce-d04b-4cc4-b65d-4b723b218ba7@9def1f60-dd5b-4bb2-ba50-ecbd7a895ce2/IncomingWebhook/ab51ac0ee3244d7aba2e07386bcf0c72/cc3e4e90-6e9b-403f-a5f9-5ebc600105c0
                body: '{"title": "Monika NPM Release", "Text": "Version: ${{ steps.package-version.outputs.current-version}}"}'
