# This workflow will run when a new Pull Request is opened or reopened, and a new issue is opened.
# This workflow only notifies Hyperjump's Microsoft Teams. Nothing else.
# WARNING: Since this PR uses pull_request_target trigger, DO NOT BUILD THE PROJECT IN THIS WORKFLOW!
# For more information: https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
# To PR reviewers: Please make sure there is no build steps in this workflow.

name: Notify Teams

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened, reopened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Set variables
      id: set_variables
      run: |
        if [ "$GITHUB_EVENT_NAME" = "issues" ]; then
            echo "::set-output name=webhook_title::New issue opened: ${{ github.event.issue.title }}" 
            echo "::set-output name=webhook_text::${{ github.event.issue.html_url }}" 
        else
            echo "::set-output name=webhook_title::New PR opened: ${{ github.event.pull_request.title }}" 
            echo "::set-output name=webhook_text::${{ github.event.pull_request.html_url }}"   
        fi
      env:
        GITHUB_EVENT_NAME: ${{ github.event_name }}
    - name: Notify Teams
      uses: joelwmale/webhook-action@fd99bb3b8272237103e349e9bb4d9b0ead9a217c
      with:
        url: ${{secrets.HYPERJUMP_TEAMS_SYMON_WEBHOOK}}
        body: '{"title": "${{ steps.set_variables.outputs.webhook_title }}", "text": "${{ steps.set_variables.outputs.webhook_text }}"}'
